### ISSUE TITLE
Best Practices or Bad Practices? Page Transition refactoring issue.

### ISSUE THREAD

**Issue by agileseph** [calabash/calabash-android#579]
I would like discuss the Xamarin example from http://developer.xamarin.com/guides/testcloud/calabash/xplat-best-practices/ . I am interested in aspect of implementation the page transition.

# The question: Is it best practice to use if-s for page detection?

My Cons:
1) It is against testing methodology fundamentals. The concept of test scenario has been broken if some behavior as page transitions processed from the actual perspective. Page transitions should not be based on the actual information because it is already expected information that should be implemented in test scenario steps.
2) Using of if-s with wait_for_page methods increase extremely performance (it increases the number of web requests with element_exists and other commands). So if some app has many page transitions, then it is increased the number of if-s with current_page? or element_exists?. So it exists Performance Issue.
3) It has non-simple logic for debugging if app has many different page transitions. Costs of automation support is important,

The actual code as:

```
if main_page.current_page?
      main_page.await
    else
      self
    end
```
can be refactored to one level up (to StepDefinitions or Abstract Steps) as:

## Variant I (move page transition to Abstract Step):
From:
```
Scenario: Invalid login to WordPress.com blog
  Given I am about to login
  When I enter invalid credentials
  Then I am presented with an error message to correct credentials
```
To:
```
Scenario: Invalid login to WordPress.com blog
  Given I am about to login
  When I enter invalid credentials
  Then I am on WordPressCom page
  Then I am presented with an error message to correct credentials
...
Scenario: Valid login to WordPress.com blog
  Given I am about to login
  When I enter valid credentials
  Then I am on Main page
  And other staff
```
## Variant II (move page transition to Step Definition):

From:
```
When /^I enter invalid credentials$/ do
  @page = @page.login(USERS[:invalid])
end
```
To:
```
When /^I enter invalid credentials$/ do
  @page.login(USERS[:invalid])
  @page.await
end
...
When /^I enter valid credentials$/ do
  @page.login(USERS[:valid])
  @page = page(MainPage).await
end
```

Finally, this refactoring does not destroy the basic x-platform concept.

**Comment by jmoody** [comment]
@agileseph This is a good post.  We discussed this around the office a bit.  I will try to find some time provide some meaningful comments in the next few days.

**Comment by agileseph** [comment]
Thank you, @jmoody. 
I did not investigated all Pros and Cons. It's very important to look on the issue from different perspectives and discuss it.
I'm looking forward to getting your answer.

**Comment by jmoody** [comment]
The x-platform example is not perfect and the documentation is not perfect either.

For example, using `@page` is not a best practice.  `@page` is opaque to the reader:  you cannot know, just by looking at it, what the value of `@page` at the start of a Step.

The best practice is to call `page(YourPage)` whenever you need to interact with a page.  Making page objects is cheap - it doesn't take a lot of time or consume much memory.

If I understand your argument correctly, I agree with you - branching like this is not great.

I would prefer to see:

```
def login_with_valid_credentials
end

def login_with_invalid_credentials
end
```

I prefer this:

```
# Good
Scenario: Invalid login to WordPress.com blog
  Given I am about to login
  When I enter invalid credentials
  Then I am presented with an error message to correct credentials
```

over this:

```
Scenario: Invalid login to WordPress.com blog
  Given I am about to login
  When I enter invalid credentials
  Then I am on WordPressCom page
  Then I am presented with an error message to correct credentials
```

because the test is really about invalid credentials.  I don't care (in this case) what page I am on when I see the error message.

The will be cases where I _do_ care about the page I am on.  For example, suppose the design changes and the message is presented on a new page: InvalidLoginPage.  Then I might write my Scenario like this:

```
Scenario: Invalid login to WordPress.com blog
  Given I am about to login
  When I enter invalid credentials
  Then I see the invalid login page
  Then I am presented with an error message to correct credentials
```

during development.  But I would almost certainly delete the:

```
  Then I see the invalid login page
```

once I was done implementing the new behavior.

I _might_ keep it for a while if I was trying to demonstrate a bug has been fixed to a client.

**Comment by agileseph** [comment]
@jmoody, 
thank you for the answer. I share the your point of view.
