### ISSUE TITLE
Swipe right/left not working

### ISSUE THREAD

**Issue by ldasilvaNZ11** [calabash/calabash-android#761]
I've tried to use 'swipe left/right' as well as 'pan left/right' to try bring menu_drawer into the screen, but have not succeed. 

Here is the pan command used in my calabash steps file:

When(/^I pan left$/) do
  pan("* id:'drawer_id_here'",:left)
end  

Any thoughts?

**Comment by TobiasRoikjer** [comment]
What is the size of "* id:'drawer_id_here'"? Turn on visual gestures in the developer options on your device to see the size of the pan.

**Comment by ldasilvaNZ11** [comment]
I think the issue is that the drawer is hidden in the right hand side of the screen, and method is trying to get drawer id which is not present in this current screen.

Normally a simple swipe left is enough to bring drawer into the main screen when performing manual testing.

The "drawer_id_here" size would be measured by something along this lines [210,0][1080,1776] ?

Another thing, my calabash_steps.rb file is currently set to:

`require 'calabash-android/calabash_steps'`

When(/^I pan left$/) do
 
  pan("* id:'drawer_id_here'",:left)
 
end

When(/^I pan right$/) do

pan("* id:'drawer_id_here'",:right)

end

Does the command `require 'calabash-android/calabash_steps'` bring all of the latest syntax changes made to calabash (meaning it updates automatically, as long as my calabash tool is up to date)?

**Comment by TobiasRoikjer** [comment]
Syntax highlighting in general can be a bit tricky to set up. Just use `pan_left` to do a general right to left swipe on the device screen.

**Comment by ldasilvaNZ11** [comment]
Do you mean by that using `pan_left` syntax on my_first.feature file (gherkins statements) or using  pan_left to define a method under calabash_steps.br?

Sorry that's probably another silly question, I am just trying to learn how to use the tool and its syntax. Thanks for your help so far!

**Comment by TobiasRoikjer** [comment]
You should define it in your steps. We ALWAYS recommend to use the actual Calabash API, not the predefined steps. 

The Cucumber features are not code, they are descriptions of the *expected behaviour*. These are *tied* to an actual test written using Calabash. If these tests pass, we can be more confident that the application *behaves as we expect*. The Cucumber way of tying behaviour to tests are through step definitions. This is how your feature files should read: https://github.com/calabash/x-platform-example/blob/master/features/login.feature
